### ISSUE TITLE
TODO: Work on a new major version that only target 4.2+

### ISSUE THREAD

**Issue by byroot** [byroot/activerecord-typedstore#24]
ActiveRecord's internals heavily changed for 4.2, and it now offer public API that would make TypedStore way simpler.

A `1.0` targeting only 4.2+ would be interesting and less hacky.

**Comment by donbobka** [comment]
:+1:

**Comment by yesmeck** [comment]
Any update?

**Comment by byroot** [comment]
No sorry I haven't started yet.

**Comment by yesmeck** [comment]
@byroot I'd like to do this issue if you don't have time.

**Comment by byroot** [comment]
@yesmeck feel free to take a stab at it!

**Comment by byroot** [comment]
Fixed in `1.0.0.beta1`
