### ISSUE TITLE
undefined method 'accessor' for ActiveRecord::Type::Value

### ISSUE THREAD

**Issue by Antiarchitect** [byroot/activerecord-typedstore#33]
Rails 4.2.4, activerecord-typedstore 0.6.1. When I try to instanciate record with decimal typed value described. I get this:

    NoMethodError: undefined method `accessor' for #<ActiveRecord::Type::Value:0x0000000a097270>
        from /home/andrey/.rvm/gems/ruby-2.2.3@medm/gems/activerecord-4.2.4/lib/active_record/store.rb:132:in `store_accessor_for'
        from /home/andrey/.rvm/gems/ruby-2.2.3@medm/gems/activerecord-4.2.4/lib/active_record/store.rb:121:in `read_store_attribute'
        from /home/andrey/PROJECTS/activerecord-typedstore/lib/active_record/typed_store/extension.rb:118:in `write_store_attribute'

**Comment by byroot** [comment]
That's strange. Decimals are part of the test suite :/

I'll see what I can do, but a reproduction gist would tremendously help.

You could base it off Rails's repro template: https://github.com/rails/rails/blob/adfb823af52d368fa4d88731a9809a314ad884ad/guides/bug_report_templates/active_record_gem.rb

**Comment by Antiarchitect** [comment]
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  # Activate the gem you are reporting the issue against.
  gem 'activerecord', '4.2.4'
  gem 'sqlite3'
  gem 'activerecord-typedstore', '0.6.1'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.text :data
  end
end

class Post < ActiveRecord::Base

  module DummyCoder
    extend self

    def load(data)
      data || {}
    end

    def dump(data)
      data || {}
    end
  end

  typed_store :meta, coder: DummyCoder do |s|
    s.decimal :value
  end
end

class BugTest < Minitest::Test
  def test_association_stuff
    post = Post.create!(value: 36.6)
    post.comments << Comment.create!

    assert_equal 1, post.comments.count
  end
end

**Comment by byroot** [comment]
```ruby
t.text :data
```

```
typed_store :meta
```

`:data != :meta`. So I think it's simply due to a typo. Please re-open if I'm wrong.

**Comment by Antiarchitect** [comment]
@byroot Reproduced more thoroughly:

    begin
      require 'bundler/inline'
    rescue LoadError => e
      $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
      raise e
    end

    gemfile(true) do
      source 'https://rubygems.org'
      # Activate the gem you are reporting the issue against.
      gem 'activerecord', '4.2.4'
      gem 'sqlite3'
      gem 'activerecord-typedstore', '0.6.1'
    end

    require 'active_record'
    require 'minitest/autorun'
    require 'logger'

    # Ensure backward compatibility with Minitest 4
    Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

    # This connection will do for database-independent bug reports.
    ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
    ActiveRecord::Base.logger = Logger.new(STDOUT)

    ActiveRecord::Schema.define do
      create_table :posts, force: true do |t|
        t.integer :author_id
        t.text :data
      end
      create_table :authors, force: true do |t|
      end
    end

    class Post < ActiveRecord::Base
      belongs_to :author
    end

    class Author < ActiveRecord::Base
      has_one :post

      module DummyCoder
        extend self

        def load(data)
          data || {}
        end

        def dump(data)
          data || {}
        end
      end

      delegate :data, :data_will_change!, :data_changed?, to: :bound_post

      def bound_post
        @bound_post ||= build_post
      end

      typed_store :data, coder: DummyCoder do |s|
        s.decimal :value
      end
    end

    class BugTest < Minitest::Test
      def test_association_stuff
        Author.create!(value: 36.6)

        assert_equal 1, Author.count
      end
    end

**Comment by byroot** [comment]
Oh! I see. You can't define a store on something that isn't a real attribute. TypedStore need to read the column information from ActiveRecord.

If you really wish to delegate this column, you can still do it this way:

```ruby
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  # Activate the gem you are reporting the issue against.
  gem 'activerecord', '4.2.4'
  gem 'sqlite3'
  gem 'byebug'
  gem 'activerecord-typedstore', '0.6.1'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.integer :author_id
    t.text :data
  end
  create_table :authors, force: true do |t|
  end
end

class Post < ActiveRecord::Base
  belongs_to :author

  typed_store :data do |s|
    s.decimal :value
  end
end

class Author < ActiveRecord::Base
  has_one :post

  delegate :value, :value=, to: :bound_post

  def bound_post
    @bound_post ||= build_post
  end
end

class BugTest < Minitest::Test
  def test_association_stuff
    Author.create!(value: 36.6)

    assert_equal 1, Author.count
  end
end
```

**Comment by Antiarchitect** [comment]
Exactly, this is my current workaround. But this only works when your bound model class and parent class is one to one.

**Comment by Antiarchitect** [comment]
Think for normal situations that is not a bug.
