### ISSUE TITLE
Add Rails 5.1 support

### ISSUE THREAD

**Issue by benjaminwood** [byroot/activerecord-typedstore#49]
Now that Rails 5.1 is officially out, it'd be great to add support here.

There are a couple of forks already that change the gemspec to allow bundling with Rails 5.1. My applications test pass with one of these forks, but that's as far as I've made it so far.

**Comment by byroot** [comment]
You can test it using the master branch, I'll cut a new release soon if no issue is reported.

**Comment by benjaminwood** [comment]
Cool, thanks @byroot.
