### ISSUE TITLE
Release a new version with the latest changes

### ISSUE THREAD

**Issue by aardvarkk** [byroot/activerecord-typedstore#74]
I believe I'm currently unable to use the `IdentityCoder` because the gem isn't properly requiring it. This was fixed in https://github.com/byroot/activerecord-typedstore/pull/70, but that pull request was merged two weeks after the latest release. Please release a new version including those changes so the `IdentityCoder` is available.

**Comment by rafaelfranca** [comment]
The release will happen 🔜! In the meantime, bundler is your friend and allows you to use gems pointing to github.

**Comment by aardvarkk** [comment]
Yep, will do, thanks!

**Comment by rafaelfranca** [comment]
Done!

**Comment by aardvarkk** [comment]
... whoa, that *was* fast. Thanks!
