### ISSUE TITLE
Rails 7, Can't find element with where in jsonb field

### ISSUE THREAD

**Issue by mario-amazing** [byroot/activerecord-typedstore#99]
I can't find any element with where condition `User.where('settings @> ?', '{"notify_new_appointment":true}').first`
 Because with `typed_store` field saves in format:
 `"---\nnotify_new_appointment: true\n"` #PG jsonb  field
 Expected format(without typed_store): 
 `{"notify_new_appointment": true}`  # works as expected with jsonb `where` queries
 
My simple typed_store configuraiton:
  ```ruby
  typed_store :settings  do |s|
    s.boolean :notify_new_appointment
  end
```
Rails 7
activerecord-typedstore (1.5.1)

**Comment by byroot** [comment]
The default seraiizer is YAML. You have to specify a different one if you wish to use JSONB.
